# Generated by Django 2.1.5 on 2019-09-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='checkup_price',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='confirm_password',
        ),
    ]
