# Generated by Django 2.1.5 on 2019-09-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('notifications', '0002_commentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentnotification',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='doctor_notify', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='commentnotification',
            name='comment',
            field=models.ForeignKey(on_delete='CASCADE', related_name='comment_notify', to='doctor.Comment'),
        ),
    ]
