# Generated by Django 2.1.5 on 2019-09-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190907_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentnotification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='CommentNotification',
        ),
    ]
